<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../ImageMatcher.cs" Link="ImageMatcher.cs" />
    <Compile Include="../../Models.cs" Link="Models.cs" />
    <Compile Include="../../InputSimulator.cs" Link="InputSimulator.cs" />
  </ItemGroup>
</Project>
