$ErrorActionPreference = 'Stop'

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$projectFile = Join-Path $projectRoot 'ClickyBot.csproj'
$projectXml = [xml](Get-Content -LiteralPath $projectFile -Raw)
$version = [string](($projectXml.Project.PropertyGroup | Where-Object { $_.Version } | Select-Object -First 1).Version)
if ([string]::IsNullOrWhiteSpace($version)) {
    throw 'ClickyBot.csproj does not define a release version.'
}
$env:DOTNET_CLI_HOME = Join-Path $projectRoot '.dotnet-cli'
$env:DOTNET_NOLOGO = '1'
$distRoot = Join-Path $projectRoot 'dist'
$artifactRoot = Join-Path $projectRoot 'artifacts'
$publishRoot = Join-Path $artifactRoot 'publish-win-x64'
$setupPublishRoot = Join-Path $artifactRoot 'setup-publish-win-x64'
$installerStaging = Join-Path $artifactRoot 'installer-staging'
$portableRoot = Join-Path $distRoot "ClickyBot-$version-win-x64"
$portableZip = Join-Path $distRoot "ClickyBot-Portable-$version-win-x64.zip"
$setupPath = Join-Path $distRoot "ClickyBot-Setup-$version.exe"
$setupProject = Join-Path $PSScriptRoot 'ClickyBotSetup.csproj'

foreach ($path in @($publishRoot, $setupPublishRoot, $installerStaging, $portableRoot)) {
    if (Test-Path -LiteralPath $path) {
        Remove-Item -LiteralPath $path -Recurse -Force
    }
}
New-Item -ItemType Directory -Force -Path $distRoot, $artifactRoot, $publishRoot, $setupPublishRoot, $installerStaging, $portableRoot | Out-Null
if (Test-Path -LiteralPath $setupPath) {
    Remove-Item -LiteralPath $setupPath -Force
}

$dotnet = (Get-Command dotnet -ErrorAction Stop).Source
& $dotnet publish $projectFile -c Release -r win-x64 --self-contained true `
    -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true `
    -p:PublishTrimmed=false -p:DebugType=None -o $publishRoot
if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed with exit code $LASTEXITCODE."
}

Copy-Item -Path (Join-Path $publishRoot '*') -Destination $portableRoot -Recurse -Force
Copy-Item -Path (Join-Path $publishRoot '*') -Destination $installerStaging -Recurse -Force

if (Test-Path -LiteralPath $portableZip) {
    Remove-Item -LiteralPath $portableZip -Force
}
Compress-Archive -Path (Join-Path $portableRoot '*') -DestinationPath $portableZip -CompressionLevel Optimal

& $dotnet publish $setupProject -c Release -r win-x64 --self-contained true `
    -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true `
    -p:PublishTrimmed=false -p:DebugType=None -p:Version=$version `
    -p:AssemblyVersion="$version.0" -p:FileVersion="$version.0" -o $setupPublishRoot
if ($LASTEXITCODE -ne 0) {
    throw "ClickyBot setup publish failed with exit code $LASTEXITCODE."
}
Copy-Item -LiteralPath (Join-Path $setupPublishRoot 'ClickyBotSetup.exe') -Destination $setupPath -Force

# Keep the maintained framework-dependent build and user macro folder in
# bin\Release-macros, but remove publish-only runtime folders generated by
# dotnet so the release directory stays tidy.
foreach ($generatedOutput in @(
    (Join-Path $projectRoot 'bin\Release-macros\net8.0-windows'),
    (Join-Path $projectRoot 'bin\Release-macros\win-x64')
)) {
    if (Test-Path -LiteralPath $generatedOutput) {
        Remove-Item -LiteralPath $generatedOutput -Recurse -Force
    }
}

# Keep only the two distributable files in dist after a release build. All
# other paths below are generated build state and can be recreated next time.
foreach ($generatedPath in @(
    $portableRoot,
    $artifactRoot,
    (Join-Path $projectRoot '.dotnet-cli'),
    (Join-Path $projectRoot 'obj'),
    (Join-Path $PSScriptRoot 'bin'),
    (Join-Path $PSScriptRoot 'obj')
)) {
    if (Test-Path -LiteralPath $generatedPath) {
        Remove-Item -LiteralPath $generatedPath -Recurse -Force
    }
}

Write-Host "Created $setupPath"
Write-Host "Created $portableZip"
