$ErrorActionPreference = 'Stop'

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$projectFile = Join-Path $projectRoot 'ClickyBot.csproj'
$projectXml = [xml](Get-Content -LiteralPath $projectFile -Raw)
$version = [string](($projectXml.Project.PropertyGroup | Where-Object { $_.Version } | Select-Object -First 1).Version)
if ([string]::IsNullOrWhiteSpace($version)) {
    throw 'ClickyBot.csproj does not define a release version.'
}
$env:DOTNET_CLI_HOME = Join-Path $projectRoot '.dotnet-cli'
$env:DOTNET_NOLOGO = '1'
$distRoot = Join-Path $projectRoot 'dist'
$artifactRoot = Join-Path $projectRoot 'artifacts'
$publishRoot = Join-Path $artifactRoot 'publish-win-x64'
$installerAppRoot = Join-Path $artifactRoot 'installer-app-win-x64'
$portableRoot = Join-Path $distRoot "ClickyBot-$version-win-x64"
$portableZip = Join-Path $distRoot "ClickyBot-Portable-$version-win-x64.zip"
$setupPath = Join-Path $distRoot "ClickyBot-Setup-$version.exe"
$installerScript = Join-Path $PSScriptRoot 'ClickyBot.iss'

foreach ($path in @($publishRoot, $installerAppRoot, $portableRoot)) {
    if (Test-Path -LiteralPath $path) {
        Remove-Item -LiteralPath $path -Recurse -Force
    }
}
New-Item -ItemType Directory -Force -Path $distRoot, $artifactRoot, $publishRoot, $installerAppRoot, $portableRoot | Out-Null
if (Test-Path -LiteralPath $setupPath) {
    Remove-Item -LiteralPath $setupPath -Force
}

$dotnet = (Get-Command dotnet -ErrorAction Stop).Source
& $dotnet publish $projectFile -c Release -r win-x64 --self-contained true `
    -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true `
    -p:PublishTrimmed=false -p:DebugType=None -o $publishRoot
if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed with exit code $LASTEXITCODE."
}

Copy-Item -Path (Join-Path $publishRoot '*') -Destination $portableRoot -Recurse -Force

if (Test-Path -LiteralPath $portableZip) {
    Remove-Item -LiteralPath $portableZip -Force
}
Compress-Archive -Path (Join-Path $portableRoot '*') -DestinationPath $portableZip -CompressionLevel Optimal

& $dotnet publish $projectFile -c Release -r win-x64 --self-contained true `
    -p:PublishSingleFile=false -p:PublishTrimmed=false -p:DebugType=None `
    -p:Version=$version -p:AssemblyVersion="$version.0" -p:FileVersion="$version.0" `
    -o $installerAppRoot
if ($LASTEXITCODE -ne 0) {
    throw "ClickyBot installer application publish failed with exit code $LASTEXITCODE."
}

$innoCandidates = @(
    (Join-Path ${env:ProgramFiles(x86)} 'Inno Setup 6\ISCC.exe'),
    (Join-Path ${env:ProgramFiles} 'Inno Setup 6\ISCC.exe'),
    (Join-Path ${env:LOCALAPPDATA} 'Programs\Inno Setup 6\ISCC.exe')
)
$innoCompiler = $innoCandidates | Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
if (-not $innoCompiler) {
    throw 'Inno Setup 6 was not found. Install it before building the ClickyBot setup executable.'
}
& $innoCompiler "/DMyAppVersion=$version" $installerScript
if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $setupPath)) {
    throw "Inno Setup failed with exit code $LASTEXITCODE."
}

# Keep the maintained framework-dependent build and user macro folder in
# bin\Release-macros, but remove publish-only runtime folders generated by
# dotnet so the release directory stays tidy.
foreach ($generatedOutput in @(
    (Join-Path $projectRoot 'bin\Release-macros\net8.0-windows'),
    (Join-Path $projectRoot 'bin\Release-macros\win-x64')
)) {
    if (Test-Path -LiteralPath $generatedOutput) {
        Remove-Item -LiteralPath $generatedOutput -Recurse -Force
    }
}

# Keep only the two distributable files in dist after a release build. All
# other paths below are generated build state and can be recreated next time.
foreach ($generatedPath in @(
    $portableRoot,
    $artifactRoot,
    (Join-Path $projectRoot '.dotnet-cli'),
    (Join-Path $projectRoot 'obj'),
    (Join-Path $PSScriptRoot 'bin'),
    (Join-Path $PSScriptRoot 'obj')
)) {
    if (Test-Path -LiteralPath $generatedPath) {
        Remove-Item -LiteralPath $generatedPath -Recurse -Force
    }
}

Write-Host "Created $setupPath"
Write-Host "Created $portableZip"
